config/routes.rb
Packtrkr::Application.routes.draw do
  resources :packs

end

app/models/pack.rb
class Pack < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  # GET /packs
  # GET /packs.json
  def index
    @packs = Pack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @packs }
    end
  end

  # GET /packs/1
  # GET /packs/1.json
  def show
    @pack = Pack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pack }
    end
  end

  # GET /packs/new
  # GET /packs/new.json
  def new
    @pack = Pack.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pack }
    end
  end

  # GET /packs/1/edit
  def edit
    @pack = Pack.find(params[:id])
  end

  # POST /packs
  # POST /packs.json
  def create
    @pack = Pack.new(params[:pack])

    respond_to do |format|
      if @pack.save
        format.html { redirect_to @pack, notice: 'Pack was successfully created.' }
        format.json { render json: @pack, status: :created, location: @pack }
      else
        format.html { render action: "new" }
        format.json { render json: @pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /packs/1
  # PUT /packs/1.json
  def update
    @pack = Pack.find(params[:id])

    respond_to do |format|
      if @pack.update_attributes(params[:pack])
        format.html { redirect_to @pack, notice: 'Pack was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packs/1
  # DELETE /packs/1.json
  def destroy
    @pack = Pack.find(params[:id])
    @pack.destroy

    respond_to do |format|
      format.html { redirect_to packs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packs_helper.rb
module PacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Packtrkr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/packs/_form.html.erb
<%= form_for(@pack) do |f| %>
  <% if @pack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pack.errors.count, "error") %> prohibited this pack from being saved:</h2>

      <ul>
      <% @pack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unitnumber %><br />
    <%= f.number_field :unitnumber %>
  </div>
  <div class="field">
    <%= f.label :charterOrg %><br />
    <%= f.text_field :charterOrg %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :primaryContact %><br />
    <%= f.number_field :primaryContact %>
  </div>
  <div class="field">
    <%= f.label :charterDate %><br />
    <%= f.date_select :charterDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/packs/edit.html.erb
<h1>Editing pack</h1>

<%= render 'form' %>

<%= link_to 'Show', @pack %> |
<%= link_to 'Back', packs_path %>

app/views/packs/index.html.erb
<h1>Listing packs</h1>

<table>
  <tr>
    <th>Unitnumber</th>
    <th>Charterorg</th>
    <th>String</th>
    <th>Primarycontact</th>
    <th>Charterdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @packs.each do |pack| %>
  <tr>
    <td><%= pack.unitnumber %></td>
    <td><%= pack.charterOrg %></td>
    <td><%= pack.string %></td>
    <td><%= pack.primaryContact %></td>
    <td><%= pack.charterDate %></td>
    <td><%= link_to 'Show', pack %></td>
    <td><%= link_to 'Edit', edit_pack_path(pack) %></td>
    <td><%= link_to 'Destroy', pack, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pack', new_pack_path %>

app/views/packs/new.html.erb
<h1>New pack</h1>

<%= render 'form' %>

<%= link_to 'Back', packs_path %>

app/views/packs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Unitnumber:</b>
  <%= @pack.unitnumber %>
</p>

<p>
  <b>Charterorg:</b>
  <%= @pack.charterOrg %>
</p>

<p>
  <b>String:</b>
  <%= @pack.string %>
</p>

<p>
  <b>Primarycontact:</b>
  <%= @pack.primaryContact %>
</p>

<p>
  <b>Charterdate:</b>
  <%= @pack.charterDate %>
</p>


<%= link_to 'Edit', edit_pack_path(@pack) %> |
<%= link_to 'Back', packs_path %>